### ISSUE TITLE
Error response from daemon: dockerfile parse error line 17: unknown instruction: YAMLLINT

### ISSUE THREAD

**Issue by kenorb** [MonolithProjects/action-molecule#1]
Build for v1.4.2 fails with:

> Error response from daemon: dockerfile parse error line 17: unknown instruction: YAMLLINT

See: <https://github.com/MonolithProjects/action-molecule/actions/runs/714140130>

**Comment by MonolithProjects** [comment]
Hey thanks for your issue. That bug was [fixed](https://github.com/MonolithProjects/action-molecule/commit/d3f65e0996675a12045c8ea28d6e4724d079fa20) some time ago (basically i noticed it immediately i created the release v1.4.2 and pushed a hotfix into the same release). So i am wondering how come you hit that issue now. 

But anyway... i just released v1.4.3 with updated base image.
